### ISSUE TITLE
Word not found

### ISSUE THREAD

**Issue by AndresKolb** [DeepLcom/deepl-php#11]
Hi, as far as I know, when a word is not found, DeepL will try to guess or just return the same entry. 
Is it possible to know when that happens? or to have the option to avoid it altogether? sometimes it's better to get a 'not found' message/error than a wild guess due to a misspelling.
Thank you for this, by the way, it's very useful!
Andres

**Comment by seekuehe** [comment]
Hi Andres, the API attempts auto-detection when `source_lang` is not specified, so it is recommended to specify this prop in the request whenever possible.

At the moment, we do not have concrete plans to change this behavior but should this be modified, our [API docs](https://www.deepl.com/docs-api/translate-text/translate-text/) will reflect this update.
