### ISSUE TITLE
Feature request: Make it possible to retrieve billing period for usage

### ISSUE THREAD

**Issue by sypets** [DeepLcom/deepl-php#21]
This probably requires an API change as well.

I would like to know to what time frame the "usage" applies to. I have count used and a limit (for characters, document and team documents). I assume it applies to current billing period, which is in our case monthly but the start of the time interval may vary (for example in our case it is February 26, 2023 - March 25, 2023). So you cannot assume the month starts with day 1, e.g. February 1. 

For example this is the output I would like to display:

```
characters:
20% used (February 26, 2023 - March 25, 2023)

```
I can use the timeframe as fixed string in my case, but if people want to supply further PHP packages based on this API for public use, it would be helpful to be able to read this from the API.

My wish would be to extend the Usage information fetched from the DeepL API and Usage class in deepl-php.

https://www.deepl.com/docs-api/general/get-usage/

**Comment by JanEbbing** [comment]
Hi, I checked internally and this is currently not planned as it's blocked by another project. I agree that we should expose this information however, and we will revisit this once the other project is completed.
