### ISSUE TITLE
Edit entry in glossary

### ISSUE THREAD

**Issue by agenceKanvas** [DeepLcom/deepl-php#23]
Hi !
Is there a way to edit / delete an entry in the glossary ? 
Thanks

**Comment by JanEbbing** [comment]
Hi, we don't support editing of glossaries for technical reasons, we recommend just recreating the glossary, see [the docs for glossaries](https://www.deepl.com/docs-api/glossaries/).
Feel free to reopen if this doesn't address your issue.
