### ISSUE TITLE
Autoloading not working

### ISSUE THREAD

**Issue by grandeljay** [DeepLcom/deepl-php#25]
Hello,

I'm guessing this is not directly related to this library but I am experiencing some very strange behaviour and was hoping you could still help me.

I am working on a WordPress plugin with the following code:
```php
<?php
/**
 * [...]
 */

namespace My\Namespace;

define( 'PLUGIN_FILEPATH', __FILE__ );
define( 'DEEPL_API_HOST', 'api-free.deepl.com' );
define( 'DEEPL_API_KEY', '[...]' );

require_once __DIR__ . '/vendor/autoload.php'; // composer's autoloader
require_once __DIR__ . '/src/autoload.php'; // my own autoloader for the plugin

$plugin = new Plugin( PLUGIN_FILEPATH );
$plugin->run();

require_once '/vendor/deeplcom/deepl-php/src/Translator.php'; // Required to avoid error
$translator      = new \Deepl\Translator(DEEPL_API_KEY);
$sourceLanguages = $translator->getSourceLanguages();
```

Without manually requiring the DeepL class I get the following error:
```log
PHP Fatal error:  Uncaught Error: Class "Deepl\Translator" not found in /path/to/my/plugin/my-plugin.php:36
Stack trace:
#0 /path/to/wordpress/wp-settings.php(453): include_once()
#1 /path/to/wordpress/wp-config.php(96): require_once('C:\\laragon\\www\\...')
#2 /path/to/wordpress/wp-load.php(50): require_once('C:\\laragon\\www\\...')
#3 /path/to/wordpress/wp-admin\admin.php(34): require_once('C:\\laragon\\www\\...')
#4 {main}
  thrown in /path/to/my/plugin/my-plugin.php on line 36
```

Composer commands I have run in an attempt to fix this:
- `composer require deeplcom/deepl-php`
- `composer install`
- `composer dump-autoload`

My composer.json:
```json
{
    "require": {
        "deeplcom/deepl-php": "^1.4"
    }
}
```

I'm probably making an obvious mistake but can't see what. Please help!

Thanks in advance!

**Comment by JanEbbing** [comment]
The namespace is `DeepL`, not `Deepl`, so
`$translator      = new \Deepl\Translator(DEEPL_API_KEY);`
should be
`$translator      = new \DeepL\Translator(DEEPL_API_KEY);`

**Comment by grandeljay** [comment]
Omg, I am so sorry 😭

Thank you for responding, I really appreciate it!
