### ISSUE TITLE
instaling libreries without composer

### ISSUE THREAD

**Issue by jcparejo** [DeepLcom/deepl-php#31]
Hi. I have problem with composer and deepl libraries.

It is posible to install without composer ?

Where are the files and a simple example in php for translate deepl using a frre api

best regards

**Comment by JanEbbing** [comment]
Hi, we don't currently support using this library without composer. To do so, you simply need to download the files from this repo (Code -> Download ZIP -> extract that, or `git clone` the repository), and copy them into a `vendor` directory in your PHP project. Then you just need to `require_once('vendor/deepl-php/src/Translator.php');` all the files in `src` and you're good to go. I'm working on an `init.php` which makes it easier to use the library without composer, but I still need to test it better.

**Comment by jcparejo** [comment]
Thank you


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jcparejo** [comment]
I did it but it does work. I see a .composer on my host and i have include the  vendor /deepl-php with all files
It show a 500 error
do i have to change any file ?
i am new on it and i am a bit lost

**Comment by JanEbbing** [comment]
How did you install the dependencies of the project and when do you get which error exactly?

**Comment by jcparejo** [comment]
https://www.solalquiler.com/deepl/

I hace use FTP  to upload in .composer/vendor/dewpl-php

**Comment by JanEbbing** [comment]
Like I said, you will need to install the dependencies as well (and their dependencies), which is what composer would do for you. Check the stackoverflow link. The 500 error you get when you visit the website is just what your webserver serves to an end user, you would need to check your server's logs to get a stacktrace and see which error occurs server-side.

**Comment by jcparejo** [comment]
I have install deepl with compoer ->   composer require deeplcom/deepl-php


later i have created a php file with

$authKey = "  My deelp key"; // Replace with your key
$translator = new \DeepL\Translator($authKey);

$result = $translator->translateText('Hello, world!', null, 'fr');
echo $result->text; // Bonjour, le monde!

But it does work

later, i have create a folder deepl2 in root createing the composer project and works. 

i don know if i have to include any line more

**Comment by jcparejo** [comment]
Hi JanEbbing

I have resolved it just adding the require link to the fólder whete IS the vendor files

Thank you for your time
