### ISSUE TITLE
Usage API may not return limit 

### ISSUE THREAD

**Issue by dsgrillo** [DeepLcom/deepl-php#33]
Currently, the API is only returning the `character_count` and not the `character_limit`:

```
11:31:06 INFO      [app] DeepL API response POST https://api.deepl.com/v2/usage 200
11:31:06 DEBUG     [app] Response details: {"character_count":151629018}
```

In my use case, we only need to have the `character_count`, but the implementation discards the response if both are not present:

```
 private function buildUsageDetail(string $prefix, array $json): ?UsageDetail
    {
        $count = "{$prefix}_count";
        $limit = "{$prefix}_limit";
        if (array_key_exists($count, $json) && array_key_exists($limit, $json)) {
            return new UsageDetail($json[$count], $json[$limit]);
        }
        return null;
    }
```

**Comment by daniel-jones-deepl** [comment]
Hi @dsgrillo, thanks for reporting this. I haven't been able to reproduce this, but we're looking into it. Does the problem occur still?

**Comment by dsgrillo** [comment]
Thanks for looking into it!
Yes, it's still happening. It started around 12:00 on September 18th and has been happening since then. 
I can also add that the dashboard on the DeepL website is apparently showing wrong numbers.

**Comment by daniel-jones-deepl** [comment]
I'd like to give an update: we've reproduced the problem and pinpointed the issue; we're working on a fix.

**Comment by daniel-jones-deepl** [comment]
This issue should be fixed as of Oct 13.
