### ISSUE TITLE
php_uname() only works with a single character string

### ISSUE THREAD

**Issue by jimwins** [DeepLcom/deepl-php#54]
https://github.com/DeepLcom/deepl-php/blob/fdf86cce24718d0ca4fa237e809951ec0d4835a8/src/Translator.php#L761

This has never worked as apparently hoped, it has always just used the first character from the string, and in PHP 8.4 will throw a `ValueError` when more than one character is specified like this.

Originally reported as a bug against PHP at php/php-src#16641 by @that-guy-iain.

**Comment by that-guy-iain** [comment]
A breaking change in php-src still needs to be fixed. The documentation suggests that the string should work and there are unknown companies that may be using that string. And their code will be affected by a breaking change which was never mentioned anywhere in RFCS and would need the documentation to be quietly changed to pretend that this didn't happen. Breaking changes are bad and quietly changing documentation is even worse.

**Comment by jochensengier** [comment]
You can bypass it for now by not sending platform information:

`
$translator = new \DeepL\Translator('YOUR_AUTH_KEY', ['send_platform_info' => false]);`

**Comment by JanEbbing** [comment]
Thanks for this report and sorry for the breakage. I will release 1.10.1 today which fixes this
