### ISSUE TITLE
Contains special characters throws ConnectException: Connection timed out error

### ISSUE THREAD

**Issue by oklqaz** [DeepLcom/deepl-php#8]
Contains special characters throws ConnectException: Connection timed out error
like ! or &

**Comment by daniel-jones-deepl** [comment]
Hi @oklqaz, thanks for raising this issue. Can you share some example code? I could not reproduce it with the following code:
```
$translator = new Translator("f63c02c5-f056-..."; // Replace with your key
$result = $translator->translateText("Hello to one & all!", "en", "de")->text;
echo $result; // Outputs: "Hallo an alle und jeden!"
```

And do you know when this timeout occurred? It could be a temporary issue.

**Comment by daniel-jones-deepl** [comment]
I'm closing this issue as I cannot reproduce it without more information, but feel free to comment again in future.
